### ISSUE TITLE
Can't launch on Archlinux

### ISSUE THREAD

**Issue by microspace** [katharosada/botchallenge#9]
Hello.
I'm trying to lauch spigot server on Archlinux. 
I'm able to spawn robot, but when I give it a command from python script, I get this error:

```
[20:55:22 INFO]: micro issued server command: /spawnrobot
[20:55:31 WARN]: Failed to initialize a channel. Closing: [id: 0x7cbee057, /0:0:0:0:0:0:0:1:45048 => /0:0:0:0:0:0:0:1:26656]
java.lang.NoClassDefFoundError: com/google/protobuf/ExtensionRegistryLite
```

I've followed these instructions to lauch spigot server http://www.spigotmc.org/wiki/buildtools/#linux
I've installed maven, ant and protobuf. I've compiled robominions plugin and placed it to plugins directory. What I'm I doing wrong?

**Comment by microspace** [comment]
I don't understand anything. I give up.

**Comment by Normangorman** [comment]
What is it you're struggling to understand? Maybe I can help you?

**Comment by microspace** [comment]
I've compiled protobuf source code from here https://github.com/google/protobuf. Now, when I try to build plugin, I get these errors: 
https://gist.github.com/microspace/e63a8cd912448e3f2d94
Next week I'm going to try challenge on ubuntu machine.

**Comment by Normangorman** [comment]
The reason for this message is that you're using protobuf 3. You should use 2.5.0 instead. 2.5.0 Isn't available from the github repo but you can get it here: http://code.google.com/p/protobuf/downloads/list.

**Comment by katharosada** [comment]
OK! I found this myself when I upgraded to the latest version of spigot, it turns out it's nothing to do with Arch linux, it somehow broke with the new version. This is not a bug in spigot, it's because the plugin depends on the netty library and protobuf extension to netty. Since spigot (and Minecraft) already use netty, it was using the existing netty library and couldn't find the protobuf classes referenced from there. This is why adding the protobuf classes into spigot itself worked.

Fortunately with my latest commit, this is no longer necessary, I've shaded netty and protobufs under our own namespace so it can't be interfered with by the existing netty. You should be able to build and run the plugin without doing any weird hackery with the protobuf classes anymore. :)

**Comment by katharosada** [comment]
Just to be clear, this fixes the original reported bug, not the other error that microspace is seeing, which hopefully won't be an issue since you don't need to compile the protobuffer library anymore since the original bug is fixed.
